### ISSUE TITLE
Current state of play

### ISSUE THREAD

**Issue by pa9ey** [pa9ey/ChessChatWithKent#2]

**Comment by pa9ey** [comment]
Aronian seems to be killing it at the moment.

So... 2-0 Kent.

**Comment by pa9ey** [comment]
@AlexKent3141

**Comment by AlexKent3141** [comment]
Ah yes, 2 points for predicting a decisive result :) 

The other games all had very similar openings (all Ruy Lopez at least). Must be the GM's favourite at the moment!

**Comment by pa9ey** [comment]
The were two games that were at identical positions at one point!

**Comment by pa9ey** [comment]
Oh, actually...
Maybe just 1-0. (Because white)
@AlexKent3141

**Comment by AlexKent3141** [comment]
Ah yes, if Carlsen manages to win that will be worth 2 points.

**Comment by AlexKent3141** [comment]
Looks pretty drawn now though...
