### ISSUE TITLE
Round 1 Score

### ISSUE THREAD

**Issue by pa9ey** [pa9ey/ChessChatWithKent#4]

**Comment by pa9ey** [comment]
After 1 Result:

Kent 1 - 0 Page

**Comment by pa9ey** [comment]
After 2 results:

Kent 2.5 - 0 Page

**Comment by pa9ey** [comment]
@AlexKent3141 Hmm.

**Comment by AlexKent3141** [comment]
I'm sure you will catch up - don't give up!

**Comment by AlexKent3141** [comment]
Carlsen's pushing hard against Caruana - I hope it doesn't backfire...

**Comment by pa9ey** [comment]
I might get some points in that one...

**Comment by pa9ey** [comment]
After 3 results:

Kent 2.5 - 1.5 Page

**Comment by pa9ey** [comment]
@AlexKent3141 Come on.

**Comment by pa9ey** [comment]
I should probably go to bed, but time control makes things interesting again...

**Comment by pa9ey** [comment]
After 4 results:

Kent 2.5 - 1.5 Page

**Comment by pa9ey** [comment]
Final Round 1 Result:

Kent 2.5 - 1.5 Page
